### ISSUE TITLE
Error when running mix compile.proto for first time

### ISSUE THREAD

**Issue by danirukun** [OffgridElectric/protobuf_compiler#11]
```
mix compile.proto
** (Mix) The task "escript.install hex protobuf 0.9.0" could not be found. Did you mean "escript.install"?
```

```elixir
	  {:protobuf, "~> 0.9.0", override: true},
      {:protobuf_compiler,
       github: "OffgridElectric/protobuf_compiler",
       tag: "v0.2.0",
       only: [:dev, :test],
       runtime: false},

```

**Comment by danirukun** [comment]
Workaround is to manually run `mix escript.install hex protobuf 0.9.0`

**Comment by jeanparpaillon** [comment]
@DaniruKun thanks for testing and for your report.

**Comment by jeanparpaillon** [comment]
I think the following PR fixes this issue: https://github.com/OffgridElectric/protobuf_compiler/pull/13

However, I've just pushed an improvement: in case your app depend on `protobuf` as well as `protobuf_compiler`, plugin is compiled from your dep, to perfectly match compiler with library.
