### ISSUE TITLE
Update README example

### ISSUE THREAD

**Issue by danirukun** [OffgridElectric/protobuf_compiler#14]
In the README, the plugin mentions a `targets` parameter, however in the source code it does not exist.
Instead, there is a `dest`: https://github.com/OffgridElectric/protobuf_compiler/blob/main/lib/mix/tasks/compile.proto.ex#L53

I got it to work, but maybe for others would be nice to update the example.

**Comment by jeanparpaillon** [comment]
I value your feedback, thanks :)
